name: Build, Test, and Publish Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Detect test projects
        id: detect-tests
        shell: bash
        run: |
          if grep -rl "<IsTestProject>true" --include "*.csproj" . >/dev/null; then
            echo "has-tests=true" >> "$GITHUB_OUTPUT"
          elif grep -rl "<PackageReference Include=\"Microsoft.NET.Test.Sdk\"" --include "*.csproj" . >/dev/null; then
            echo "has-tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-tests=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Test
        if: steps.detect-tests.outputs.has-tests == 'true'
        run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal

      - name: Skip tests (no test projects found)
        if: steps.detect-tests.outputs.has-tests != 'true'
        run: echo "No test projects found. Skipping tests."

      - name: Pack NuGet package
        if: matrix.configuration == 'Release' && matrix.os == 'ubuntu-latest'
        run: dotnet pack src/MessageQueue.Core/MessageQueue.Core.csproj --configuration Release --no-build --output ./packages -p:ContinuousIntegrationBuild=true

      - name: Upload NuGet artifact
        if: matrix.configuration == 'Release' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: packages/*.nupkg

      - name: Publish NuGet package
        if: matrix.configuration == 'Release' && matrix.os == 'ubuntu-latest'
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
